// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
