name: Desktop build
permissions:
  contents: write
  
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: akroma-desktop, platform: linux/amd64, os: ubuntu-latest},
          {name: akroma-desktop.exe, platform: windows/amd64, os: windows-latest},
          {name: akroma, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
      - name: post-notice-to-twitter
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
          twitter_status: "Akroma Desktop\n\nNew Release:\nhttps://github.com/akroma-project/akroma-desktop/releases \n\n🥳"
          twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }} 
          twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }} 
          twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
          twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 