name: Desktop build
permissions:
  contents: write
  
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: akroma-desktop, platform: linux/amd64, os: ubuntu-latest},
          {name: akroma-desktop.exe, platform: windows/amd64, os: windows-latest},
          {name: akroma-desktop, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}