name: Desktop build
permissions:
  contents: write
  
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: AkromaDesktop
          build-platform: linux/amd64
          wails-build-webview2: "embed"
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: AkromaDesktop
          build-platform: darwin/universal
          wails-build-webview2: "embed"
          sign: "false"
          # sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          # sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          # sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          # sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          # sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          # sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          # sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: AkromaDesktop.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"